panel/urls.py
from django.urls import path

import panel.views as views

app_name = 'panel'
urlpatterns = [
    path('', views.panel, name='panel'),

    path('products/', views.show_products, name='products'),
    path('product/<int:product_id>', views.show_product, name='product'),
    path('product-category/<slug:category>', views.show_product_category, name='product-category'),

    path('providers/', views.show_providers, name='providers'),
    path('provider/<int:provider_id>', views.show_provider, name='provider'),

    path('clients/', views.show_clients, name='clients'),
    path('client/<int:client_id>', views.show_client, name='client'),

    path('sales/', views.show_sales, name='sales'),
    path('sale/<int:sale_id>', views.show_sale, name='sale'),

    path('deliveries/', views.show_deliveries, name='deliveries'),
]

tms/urls.py
from django.contrib import admin
from django.urls import path, include

from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('panel/', include('panel.urls'), name='panel'),
] + debug_toolbar_urls()

panel/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.FloatField(default=0.0)
    count = models.IntegerField(default=0)
    category = models.ForeignKey('ProductCategory', on_delete=models.PROTECT, blank=True,
                                 related_name='products')
    providers = models.ManyToManyField('Provider', blank=True, related_name='products')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('panel:product', kwargs={'product_id': self.id})


class ProductCategory(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('panel:product-category', kwargs={'category': self.slug})


class Provider(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('panel:provider', kwargs={'provider_id': self.id})


class Client(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('panel:client', kwargs={'client_id': self.id})


class Delivery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    provider = models.ForeignKey(Provider, on_delete=models.PROTECT)
    count = models.IntegerField(default=0)
    price_for_one = models.FloatField(default=0.0)

    def __str__(self):
        return (f'{self.product.name} (x{self.count}) ({self.price_for_one})'
                f' <- {self.provider.name} [{self.provider.id}]')


class Sale(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    client = models.ForeignKey(Client, on_delete=models.PROTECT)
    count = models.IntegerField(default=0)
    price_for_one = models.FloatField(default=0.0)

    def __str__(self):
        return (f'{self.product.name} (x{self.count}) ({self.price_for_one})'
                f' -> {self.client.name} [{self.client.id}]')

panel/views.py
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, get_object_or_404

from panel.models import Product, ProductCategory, Provider, Client, Sale, Delivery


def panel(request: HttpRequest) -> HttpResponse:
    """
    View for home page of panel
    """
    return render(request, 'panel/panel.html')


def show_products(request: HttpRequest) -> HttpResponse:
    """
    Products main page, that show table of all products
    """
    categories = ProductCategory.objects.all().order_by('id')
    products = Product.objects.all().order_by('id').select_related('category')
    context = {
        'products': products,
        'categories': categories,
    }
    return render(request, 'panel/products.html', context=context)


def show_product_category(request: HttpRequest, category: str) -> HttpResponse:
    category = get_object_or_404(ProductCategory, slug=category)
    products = category.products.all()
    context = {
        'category': category,
        'products': products,
    }
    return render(request, 'panel/product_category.html', context=context)


def show_product(request: HttpRequest, product_id: str) -> HttpResponse:
    """
    Product page, show information about product
    """
    product = get_object_or_404(Product, id=product_id)
    context = {
        'product': product,
    }
    return render(request, 'panel/product.html', context=context)


def show_providers(request: HttpRequest) -> HttpResponse:
    providers = Provider.objects.all()
    context = {
        'providers': providers,
    }
    return render(request, 'panel/providers.html', context=context)


def show_provider(request: HttpRequest, provider_id: int) -> HttpResponse:
    provider = get_object_or_404(Provider, id=provider_id)
    products = provider.products.all().select_related('category')
    context = {
        'provider': provider,
        'products': products,
    }
    return render(request, 'panel/provider.html', context=context)


def show_clients(request: HttpRequest) -> HttpResponse:
    clients = Client.objects.all()
    context = {
        'clients': clients,
    }
    return render(request, 'panel/clients.html', context=context)


def show_client(request: HttpRequest, client_id: int) -> HttpResponse:
    client = get_object_or_404(Client, id=client_id)
    context = {
        'client': client,
    }
    return render(request, 'panel/client.html', context=context)


def show_sales(request: HttpRequest) -> HttpResponse:
    sales = Sale.objects.all().select_related('product', 'client')
    context = {
        'sales': sales,
    }
    return render(request, 'panel/sales.html', context=context)


def show_sale(request: HttpRequest, sale_id: int) -> HttpResponse:
    sale = get_object_or_404(Sale, id=sale_id)
    context = {
        'sale': sale,
    }
    return render(request, 'panel/sale.html', context=context)


def show_deliveries(request: HttpRequest) -> HttpResponse:
    deliveries = Delivery.objects.all().select_related('product', 'provider')
    context = {
        'deliveries': deliveries,
    }
    return render(request, 'panel/deliveries.html', context=context)

panel/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title%}TMS Panel{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'panel/css/style.css' %}">
    </head>
    <body>
        <header class="header-page">
            <h1 class="header-heading"><a href="{% url 'panel:panel' %}">TMS Panel</a></h1>
            <menu class="header-menu">
                <li><a href="{% url 'panel:products' %}">Products</a></li>
                <li><a href="{% url 'panel:providers' %}">Providers</a></li>
                <li><a href="{% url 'panel:clients' %}">Clients</a></li>
                <li><a href="{% url 'panel:sales' %}">Sales</a></li>
                <li><a href="{% url 'panel:deliveries' %}">Deliveries</a></li>
            </menu>
        </header>

        <main class="main-page">
            {% block content %}{% endblock %}
        </main>

        <footer class="footer-page">
            <p class="footer-copy">Copyright &copy; 2025 TMS Panel</p>
        </footer>
    </body>
</html>

panel/templates/panel/client.html
{% extends 'base.html' %}

{% block title %}Client: {{ client.name }}{% endblock %}

{% block content %}
<div>
  <h1>{{ client.name }}</h1>
</div>
{% endblock %}

panel/templates/panel/clients.html
{% extends 'base.html' %}

{% block title %}Clients{% endblock %}

{% block content %}
<div>
    <div class="table-container">
        <h1>Clients</h1>
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
            </thead>
            <tbody>
            {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td><a href="{{ client.get_absolute_url }}">{{ client.name }}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
</div>
{% endblock %}

panel/templates/panel/deliveries.html
{% extends 'base.html' %}

{% block title %}Deliveries{% endblock %}

{% block content %}
<div class="products-table">
    <h1>Sales</h1>
    <div class="table-container">
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Product</th>
                <th>Provider</th>
                <th>Price for one</th>
                <th>Count</th>
            </tr>
            </thead>
            <tbody>
            {% for delivery in deliveries %}
            <tr>
                <td>{{ delivery.id }}</td>
                <td><a href="{{ delivery.product.get_absolute_url }}">{{ delivery.product.name }}</a></td>
                <td><a href="{{ delivery.provider.get_absolute_url }}">{{ delivery.provider.name }}</a></td>
                <td>${{ delivery.price_for_one }}</td>
                <td>{{ delivery.count }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

panel/templates/panel/panel.html
{% extends 'base.html' %}

{% block title %}TMS Panel{% endblock %}

{% block content %}

{% endblock %}

panel/templates/panel/product-category.html
{% extends 'base.html' %}

{% block title %}Product Category: {{ category.name }}{% endblock %}

{% block content %}
<div class="product-category">
    <h1>Product Category: {{ category.name }}</h1>
    <div class="table-container">
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Count</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                <td>{{ product.description }}</td>
                <td>${{ product.price }}</td>
                <td>{{ product.count }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

panel/templates/panel/product.html
{% extends 'base.html' %}

{% block title %}Product: {{ product.name }}{% endblock %}

{% block content %}
<div>
    <h1>{{ product.name }}</h1>
    <ul>
        <li>Category: <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a> </li>
        <li>Description: {{ product.description }}</li>
        <li>Price: ${{ product.price }}</li>
        <li>Count: {{ product.count }}</li>
    </ul>

    <div class="table-container">
        <h1>Providers</h1>
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
            </thead>
            <tbody>
            {% for provider in product.providers.all %}
            <tr>
                <td>{{ provider.id }}</td>
                <td><a href="{{ provider.get_absolute_url }}">{{ provider.name }}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
</div>
{% endblock %}

panel/templates/panel/product_category.html
{% extends 'base.html' %}

{% block title %}Product Category: {{ category.name }}{% endblock %}

{% block content %}
<div class="product-category">
    <h1>Product Category: {{ category.name }}</h1>
    <div class="table-container">
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Count</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                <td>{{ product.description }}</td>
                <td>${{ product.price }}</td>
                <td>{{ product.count }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

panel/templates/panel/products.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}
<div class="products-table">
    <h1>Poducts Table</h1>
    <div class="table-container">
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Count</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
                <td>{{ product.description }}</td>
                <td>${{ product.price }}</td>
                <td>{{ product.count }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

panel/templates/panel/provider.html
{% extends 'base.html' %}

{% block title %}Provider: {{ provider.name }}{% endblock %}

{% block content %}
<div>
  <h1>{{ provider.name }}</h1>

  <div class="products-table">
    <h1>Poducts</h1>
    <div class="table-container">
      <table>
        <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Category</th>
          <th>Description</th>
          <th>Price</th>
          <th>Count</th>
        </tr>
        </thead>
        <tbody>
        {% for product in products %}
        <tr>
          <td>{{ product.id }}</td>
          <td><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></td>
          <td><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></td>
          <td>{{ product.description }}</td>
          <td>${{ product.price }}</td>
          <td>{{ product.count }}</td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

panel/templates/panel/providers.html
{% extends 'base.html' %}

{% block title %}Providers{% endblock %}

{% block content %}
<div>
    <div class="table-container">
        <h1>Providers</h1>
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
            </tr>
            </thead>
            <tbody>
            {% for provider in providers %}
            <tr>
                <td>{{ provider.id }}</td>
                <td><a href="{{ provider.get_absolute_url }}">{{ provider.name }}</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

panel/templates/panel/sales.html
{% extends 'base.html' %}

{% block title %}Sales{% endblock %}

{% block content %}
<div class="products-table">
    <h1>Sales</h1>
    <div class="table-container">
        <table>
            <thead>
            <tr>
                <th>ID</th>
                <th>Product</th>
                <th>Client</th>
                <th>Price for one</th>
                <th>Count</th>
            </tr>
            </thead>
            <tbody>
            {% for sale in sales %}
            <tr>
                <td>{{ sale.id }}</td>
                <td><a href="{{ sale.product.get_absolute_url }}">{{ sale.product.name }}</a></td>
                <td><a href="{{ sale.client.get_absolute_url }}">{{ sale.client.name }}</a></td>
                <td>${{ sale.price_for_one }}</td>
                <td>{{ sale.count }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}